name: 'YandexCloud serverless function deploy action'
description: 'Deploy new serverless function version (including function creation if it does not exist)'
inputs:
  yc_account_id:
    description: 'YandexCloud account id'
    required: true
  yc_key_id:
    description: 'YandexCloud trusted key id'
    required: true
  yc_private_key:
    description: 'YandexCloud private key'
    required: true
  function_name:
    description: 'Function name'
    required: true
  runtime:
    description: 'Runtime for function'
    required: true
  folder_id:
    description: 'Function folder id'
    required: true
  function_entrypoint:
    description: 'Entry point of function'
    required: true
  function_description:
    description: 'Function description'
    required: false
    default: ''
  version_description:
    description: 'New function version description'
    required: false
    default: ''
  source_dir:
    description: 'Directory with function code to deploy'
    required: false
    default: '.'
  memory:
    description: 'Maximum allowed memory for function in MB'
    required: false
    default: '128'
  execution_timeout:
    description: 'Execution timeout in seconds for function in Yandex Cloud'
    required: false
    default: '15'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/mnogolososya/yc_deploy_function_action:1.8'
branding:
  icon: 'check-square'
  color: 'white'

