name: Deploy new action version

on:
  workflow_dispatch:
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
permissions:
  contents: read
  packages: write
    
jobs:
  build:
    name: Deploy new version
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.3.4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ env.REGISTRY }}
      
#     - name: Extract metadata (tags, labels) for Docker
#       id: meta
#       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#       with:
#         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
       
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-to: type=inline
          tags: test
          labels: ${{ steps.meta.outputs.labels }}
        