name: Display secrets
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secrets file
      env:
        YC_LAMBDA_DEPLOY_ACCOUNT_ID: ${{ secrets.YC_LAMBDA_DEPLOY_ACCOUNT_ID }}
        YC_LAMBDA_DEPLOY_KEY_ID: ${{ secrets.YC_LAMBDA_DEPLOY_KEY_ID }}
        YC_LAMBDA_DEPLOY_PRIVATE_KEY: ${{secrets.YC_LAMBDA_DEPLOY_PRIVATE_KEY}}
      run: |
        echo $YC_LAMBDA_DEPLOY_ACCOUNT_ID >> secrets.txt
        echo $YC_LAMBDA_DEPLOY_KEY_ID >> secrets.txt
        echo $YC_LAMBDA_DEPLOY_PRIVATE_KEY >> secrets.txt
    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
