name: Display secrets
on: [workflow_dispatch]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Get and display secrets
      env:
        YC_LAMBDA_DEPLOY_ACCOUNT_ID: ${{ secrets.YC_LAMBDA_DEPLOY_ACCOUNT_ID }}
        YC_LAMBDA_DEPLOY_KEY_ID: ${{ secrets.YC_LAMBDA_DEPLOY_KEY_ID }}
        YC_LAMBDA_DEPLOY_PRIVATE_KEY: ${{secrets.YC_LAMBDA_DEPLOY_PRIVATE_KEY}}
      run: |
        echo ${{secrets.YC_LAMBDA_DEPLOY_ACCOUNT_ID}} | sed 's/./& /g'
        echo ${{secrets.YC_LAMBDA_DEPLOY_KEY_ID}} | sed 's/./& /g'
        echo ${{secrets.YC_LAMBDA_DEPLOY_PRIVATE_KEY}} | sed 's/./& /g'
