name: test-master

on:
  push:
    branches:
      - master

jobs:
  deploy_function_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: Deploy function from directory
        uses: mnogolososya/yc_deploy_function_action@v1.1
        with:
          yc_account_id: ${{ secrets.YC_LAMBDA_DEPLOY_ACCOUNT_ID }}
          yc_key_id: ${{ secrets.YC_LAMBDA_DEPLOY_KEY_ID }}
          yc_private_key: ${{ secrets.YC_LAMBDA_DEPLOY_PRIVATE_KEY }}
          function_name: 'my-glorious-function'
          function_description: 'hello there'
          runtime: 'python39-preview'
          version_description: 'what a version!'
          function_entrypoint: 'example.code_to_deploy.handler'
          memory: 256
          execution_timeout: 7
          source_dir: './example'
          folder_id: 'b1ghsls4prhgto9om121'
          foo: 'bar'
          debug: '1'